### ISSUE TITLE
Support cloud endpoints in local dev environment

### ISSUE THREAD

**Issue by Scarygami** [GoogleWebComponents/google-apis#19]
Enhancement to https://github.com/GoogleWebComponents/google-apis/pull/18

Currently the `<google-api-loader>` only supports loading a Cloud Endpoint API from a deployed version on App Engine using `https://{{appId}}.appspot.com/_ah/api` as root.

For local testing there needs to be some way to use `http://localhost:{{port}}/_ah/api` as API root instead.

**Comment by softkot** [comment]
Can't use this element with polymer starter kit and local development endpount cause bew root property overlaps with some #document-fragment and can't be set. I think it should be renamed to somethong other than root, apiroot for example.

**Comment by Scarygami** [comment]
Hah, I just encountered a similar issue and created a new issue here: https://github.com/GoogleWebComponents/google-apis/issues/49
:)
