### ISSUE TITLE
Rename "root" in google-client-loader

### ISSUE THREAD

**Issue by Scarygami** [GoogleWebComponents/google-apis#49]
Seeing that this.root is now used to refer to the elements local DOM having a property with this name doesn't seem to be the best idea. I would suggest renaming it to `apiRoot` / `api-root`.

**Comment by ebidel** [comment]
+1

**Comment by kainlite** [comment]
I've been trying to get my endpoints working don't know what can be wrong with my code, tried both root and apiRoot, there is a question on stackoverflow: 

http://stackoverflow.com/questions/30718378/polymer-google-cloud-endpoints-golang-backend

I'm sorry if this is not the best place to ask this.

**Comment by Scarygami** [comment]
Would be nice to have a new release for this soon-ish so I can change my dependencies away from master :)

**Comment by ebidel** [comment]
Released: https://github.com/GoogleWebComponents/google-apis/releases/tag/1.0.1

**Comment by Scarygami** [comment]
Thanks :)
