### ISSUE TITLE
Multiple instances of google-maps-api seem to be causing some conflicts

### ISSUE THREAD

**Issue by govis** [GoogleWebComponents/google-apis#51]
Somewhat related to #22 

I have a page with multiple components that depend on google maps api - an input with place auto-complete and a map. So I have following tags on my page:

<pre><code>
&lt;google-maps-api on-api-load="_initAutocomplete"&gt;&lt;/google-maps-api&gt;
&lt;google-map latitude="[[latitude]]" longitude="[[longitude]]">&lt;/google-map&gt;
</code></pre>

The default value for libraries attribute on both google-maps-api and google-map is "places", so it should match. However I am getting the following error spit out in console and _initAutocomplete handler never fires:
 
<code>k[bd].maps.Load is not a function</code>

And if I take out the map tag the other works as expected. This feels like a common scenario to have some kind of geo-input and a map so I am wondering if it is supported and if so - what am I doing wrong? Thanks.

**Comment by ebidel** [comment]
Do you have a working jsbin we can try?

**Comment by govis** [comment]
I narrowed it down to google-map's <code>language</code> property. I had copied the code from google-map demo page and it had the language set to "en" whereas my google-maps-api tag did not have it set so it defaulted to '' (empty string)

<pre><code>&lt;google-maps-api on-api-load="_initAutocomplete ">&lt;/google-maps-api>
&lt;google-map latitude="[[latitude]]" longitude="[[longitude]]" language="en">&lt;/google-map>
</code></pre>

This has caused the scripts to load twice and the error:
<pre><code>&lt;script src="https://maps.gstatic.com/maps-api-v3/api/js/21/5a/main.js">&lt;/script>
&lt;script src="https://maps.gstatic.com/maps-api-v3/api/js/21/5a/places.js">&lt;/script>
&lt;script src="https://maps.gstatic.com/maps-api-v3/api/js/21/5a/main.js">&lt;/script>
&lt;script src="https://maps.gstatic.com/maps-api-v3/api/js/21/5a/places.js">&lt;/script>
</code></pre>

We can close it as similar to #22 but different property causing the conflict. If you want I can still put a sample together on jsbin, but I am not sure where you guys are hosting the polymer bits on cdn?

Thanks.

**Comment by ebidel** [comment]
Cool. Glad you tracked it down.
