### ISSUE TITLE
Do we need google-apis set to experimental by default?

### ISSUE THREAD

**Issue by AndreasGalster** [GoogleWebComponents/google-apis#63]
I've just spent about 2 hours figuring out why my app all of a sudden broke overnight. It took quite some time until I figured out that something broke due to an experimental update in the API.

I think the APIs should load a stable version by default. 

This is potentially very dangerous. I've just realized this means my app has been online with a broken map search the whole time for a day... which is pretty terrible considering my site relies mostly on the autocomplete api :/

**Comment by MeTaNoV** [comment]
really? last commit was 23 days ago, how possible?

**Comment by AndreasGalster** [comment]
Not the element itself. The element loads the API based on which API is set in the element. By default that is set to v3.exp (experimental), that's why probably tonight they made a change to the experimental API that broke something. So even if the element didn't get upated, the API with the introduced bug still gets loaded by default if you don't explicitly set it to the non-experimental API.

**Comment by MeTaNoV** [comment]
got it! :)

**Comment by ebidel** [comment]
Please use the `version` property if you want a fixed version:
https://github.com/GoogleWebComponents/google-apis/blob/master/google-maps-api.html#L69

Arguably, we should probably set `3` as the version. However I've rarely (never?) seen the experimental stuff actually break people. It's mostly new features.

**Comment by ebidel** [comment]
Going to leave this up to the app developer to freeze versions. Following our philosophy for bower deps, we want users on the latest API when using this element.
