### ISSUE TITLE
Possible to use Contacts API with google-client-loader

### ISSUE THREAD

**Issue by IchordeDionysos** [GoogleWebComponents/google-apis#65]
First is it possible to use the `Contacts API` with the `google-client-loader` because I can't find it in the API's Explorer, which confused me. In my opinion it is a very common API, so I should have been listed as a Google API ...
If it is not possible to use this API, could you implement this API? I want to use it throw the really cool and handy `google-client-loader`. 
And if it's not of your business, where should I submit a issue for that?

**Comment by ebidel** [comment]
IIRC, the contacts api isn't supported by the JS client library. You'd have to work with the protocol directly.
